name: Cypress Tests Allure

on: 
  workflow_dispatch:
  
jobs: 
  e2e-tests:
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node-18.15.0-chrome-111.0.5563.146-1-ff-111.0.1-edge-111.0.1661.62-1 # imagem container
      options: --user 1001 # user admin
    steps:
    - name: Checkout - GET CODE # Step: Pegar o código
      uses: actions/checkout@v3.5.2
    
    - name: Install Dependencies # Step: Instalar dependêncis
      run: yarn install
      
    - name: Run E2E Tests # Step: Executar testes com o comando do Allure
      run: npx cypress run

      # Adicionando configurações de 3 novos steps. 
      # https://github.com/simple-elf/allure-report-action

    - name: Get Allure history # Step: Pega os históricos de execução (lembrando que o primeiro não terá histórico)
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Test marketplace action # Step: Gera o relatório html do Allure
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: build/allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history

    - name: Deploy report to Github Pages # Step: Pegar o relatório html e publicar no GH Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history